ossf-package-analysis:
    confident/: confident/20250221/160819-npm-@visma-spcs-registry/react-common-components-4.2.6.json
reversing-labs:
    RLMA-: RLMA-2025-00547.json
    RLUA-: RLUA-2025-00311.json
