ossf-package-analysis:
    confident/: confident/20250517/051547-npm-blahblahblah-definitely-not-a-real-package-name-99.1.1.json
reversing-labs:
    RLMA-: RLMA-2025-02542.json
    RLUA-: RLUA-2025-02478.json
