ossf-package-analysis:
    confident/: confident/20241205/123746-npm-@wix-platform/velo-multilingual-helper-backend-100.100.106.json
reversing-labs:
    RLMA-: RLMA-2024-09529.json
    RLUA-: RLUA-2024-10363.json
