ossf-package-analysis:
    confident/: confident/20250611/111051-npm-@portal-reporting/report-ui-templates-100.99.99.json
reversing-labs:
    RLMA-: RLMA-2025-02978.json
    RLUA-: RLUA-2025-02936.json
