ossf-package-analysis:
    confident/: confident/20250403/171927-npm-@harvest-finance/harvest-strategy-polygon-1.0.0.json
reversing-labs:
    RLMA-: RLMA-2025-02014.json
    RLUA-: RLUA-2025-01897.json
