ossf-package-analysis:
    confident/: confident/20250320/140753-npm-com.unity.performance.profile-analyzer-99.99.0.json
reversing-labs:
    RLMA-: RLMA-2025-01248.json
    RLUA-: RLUA-2025-01204.json
