ossf-package-analysis:
    confident/: confident/20241030/154058-npm-@cb-global-design-system-tokens/tailwind-1.0.21.json
reversing-labs:
    RLMA-: RLMA-2024-09529.json
    RLUA-: RLUA-2024-10363.json
