ossf-package-analysis:
    confident/: confident/20250602/101423-npm-@seo-frontend-components/card-blog-entry-1.999.2.json
reversing-labs:
    RLMA-: RLMA-2025-02978.json
    RLUA-: RLUA-2025-02936.json
