ossf-package-analysis:
    confident/: confident/20241202/214938-npm-spinal-env-viewer-plugin-group-manager-service-10.1.10.json
reversing-labs:
    RLMA-: RLMA-2024-09529.json
    RLUA-: RLUA-2024-10363.json
