ossf-package-analysis:
    confident/: confident/20250703/123837-npm-@emersonecologics/emerson-angular-trove-99.99.99.json
reversing-labs:
    RLMA-: RLMA-2025-03500.json
    RLUA-: RLUA-2025-03475.json
