ossf-package-analysis:
    confident/: confident/20250218/201054-npm-mygcpconfusedfunctionpocmaliciouspackage-1.0.5.json
reversing-labs:
    RLMA-: RLMA-2025-00547.json
    RLUA-: RLUA-2025-00311.json
