ossf-package-analysis:
    confident/: confident/20241213/120217-npm-@flutteruki-gaming/test-eslint-config-flutteruki-gaming-1.6.2.json
reversing-labs:
    RLMA-: RLMA-2024-11212.json
    RLUA-: RLUA-2024-11114.json
