ossf-package-analysis:
    confident/: confident/20250622/074707-npm-handelsblatt-hypesignals-ui-components-99.99.0.json
reversing-labs:
    RLMA-: RLMA-2025-03500.json
    RLUA-: RLUA-2025-03475.json
