ossf-package-analysis:
    confident/: confident/20250512/095326-npm-com.unity.render-pipelines.universal-config-1.0.0.json
reversing-labs:
    RLMA-: RLMA-2025-02542.json
    RLUA-: RLUA-2025-02478.json
