ossf-package-analysis:
    confident/: confident/20250218/201546-npm-mygcpconfusedfunctionpocmaliciouspackage-1.0.6.json
reversing-labs:
    RLMA-: RLMA-2025-00547.json
    RLUA-: RLUA-2025-00311.json
