ossf-package-analysis:
    confident/: confident/20250404/005552-npm-@fraudprevention/device-intelligence-100.99.100.json
reversing-labs:
    RLMA-: RLMA-2025-02014.json
    RLUA-: RLUA-2025-01897.json
