ossf-package-analysis:
    confident/: confident/20241225/093829-npm-twilio-voice-react-native-reference-server-1.1.0.json
reversing-labs:
    RLMA-: RLMA-2024-11212.json
    RLUA-: RLUA-2024-11114.json
