ossf-package-analysis:
    confident/: confident/20250514/122045-npm-@walmart-dataventures/integrated-components-2.0.1.json
reversing-labs:
    RLMA-: RLMA-2025-02542.json
    RLUA-: RLUA-2025-02478.json
