ossf-package-analysis:
    confident/: confident/20250301/021918-npm-esm-appdynamics-grafana-react-datasource-2.0.0.json
reversing-labs:
    RLMA-: RLMA-2025-00547.json
    RLUA-: RLUA-2025-00311.json
