ossf-package-analysis:
    confident/: confident/20250602/101417-npm-@seo-frontend-components/card-blog-carousel-1.999.1.json
reversing-labs:
    RLMA-: RLMA-2025-02978.json
    RLUA-: RLUA-2025-02936.json
